var rootDir = "js/battle/"
document.write("<script src=\"" + rootDir + "creatures/attributes/CreatureAttributes.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/display/CreatureDisplay.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/display/DisplayManager.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/moves/BattleMove.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/moves/AttackMove.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/moves/CreatureMoves.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/moves/DefenseMove.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/BattleCreature.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/dataloader/kitties/KittyAttacks.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/dataloader/kitties/KittyDataLoader.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/display/animation/AttackAnimations.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "creatures/display/animation/EndGameAnimation.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "damage/BattleDamage.js" + "\"></script>");
document.write("<script src=\"" + rootDir + "BattleGame.js" + "\"></script>");
